"""Reconstruct the attack an adversary would actually run against a password.

The strength score answers "how strong is this?". This module answers the more
useful question: *how would it fall?* It turns the detected patterns into the
ordered stages a real cracker works through — breach corpus first, then
wordlists and rules, then keyboard and sequence generators, and only then
brute force over whatever is genuinely random.

The arithmetic is deliberately tied to :mod:`password_auditor.strength`: each
stage's guess count is ``2 ** (bits that stage has to resolve)``, so the
product of every stage equals ``2 ** effective_bits`` — the same number the
score comes from. The replay is a different *view* of the score, not a second,
disagreeing estimate.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from password_auditor.hibp import BreachResult
from password_auditor.strength import (
    GUESSES_PER_SECOND,
    StrengthResult,
    humanize_seconds,
)

# How a cracker attacks each pattern kind, and roughly in what order. Lower
# sorts earlier when guess counts tie: these are the cheap, obvious tries.
_STRATEGY: dict[str, tuple[str, str]] = {
    "dictionary_word": (
        "Wordlist + mangling rules",
        "Common bases run through capitalisation, leetspeak and affix rules - "
        "the first thing every cracking tool tries",
    ),
    "reversed_word": (
        "Wordlist, reversed",
        "A standard rule in hashcat and John the Ripper, applied to the same "
        "wordlist",
    ),
    "keyboard_walk": (
        "Keyboard-adjacency generator",
        "Walks enumerated directly from the keyboard layout, so length here "
        "costs the attacker almost nothing",
    ),
    "sequence": (
        "Sequence generator",
        "Ascending and descending runs over letters and digits",
    ),
    "repeated_char": (
        "Repetition rules",
        "A single character padded out; the rule engine generates these for free",
    ),
    "repeated_block": (
        "Repetition rules",
        "A repeated block, generated by duplication rules from the shorter unit",
    ),
    "year": (
        "Date and year list",
        "Years 1900-2099 are appended to every candidate as a matter of course",
    ),
    "date": (
        "Date and year list",
        "Common numeric date formats, enumerated exhaustively",
    ),
}

BREACH_STEP = (
    "Breach corpus lookup",
    "The password is already in the Pwned Passwords corpus, which is sorted by "
    "frequency. An attacker does not search for it - they look it up",
)

BRUTE_STEP = "Exhaustive brute force"


@dataclass
class AttackStep:
    """One stage of the reconstructed attack."""

    label: str
    detail: str
    guesses: float
    bits: float
    kind: str  # "breach" | "pattern" | "brute"
    span: tuple[int, int] | None = None
    bypassed: bool = False

    @property
    def guess_display(self) -> str:
        return format_guesses(self.guesses)


@dataclass
class AttackPlan:
    """The full reconstructed attack, cheapest stage first."""

    steps: list[AttackStep] = field(default_factory=list)
    total_guesses: float = 1.0
    shortcut: bool = False  # cracked by breach lookup, bypassing the work below

    @property
    def total_seconds(self) -> float:
        return self.total_guesses / GUESSES_PER_SECOND

    @property
    def total_display(self) -> str:
        return humanize_seconds(self.total_seconds)

    @property
    def headline(self) -> str:
        """One sentence summarising how the password falls."""
        if self.shortcut:
            return "Cracked instantly by lookup - it is already in the corpus."
        if not self.steps:
            return "Nothing to attack."
        if len(self.steps) == 1 and self.steps[0].kind == "brute":
            return (
                f"Only brute force applies: {format_guesses(self.total_guesses)} "
                f"guesses, {self.total_display}."
            )
        plural = "" if len(self.steps) == 1 else "s"
        return (
            f"{len(self.steps)} stage{plural}, "
            f"{format_guesses(self.total_guesses)} guesses, {self.total_display}."
        )


def format_guesses(guesses: float) -> str:
    """Render a guess count compactly: 2^n for big numbers, digits for small."""
    if guesses < 1000:
        return f"{round(guesses):,}"
    exponent = math.log2(guesses)
    if exponent < 70:
        return f"2^{exponent:.0f} (~{guesses:.1e})"
    return f"2^{exponent:.0f}"


def plan_attack(
    strength: StrengthResult, breach: BreachResult | None = None
) -> AttackPlan:
    """Build the attack plan for an already-scored password."""
    bits_per_char = (
        math.log2(strength.pool_size) if strength.pool_size > 1 else 0.0
    )

    steps: list[AttackStep] = []

    # One stage per detected pattern: the attacker only has to resolve the
    # entropy the pattern did not already give away.
    for finding in strength.findings:
        label, detail = _STRATEGY.get(
            finding.kind, ("Pattern generator", "A recognised, enumerable pattern")
        )
        bits = finding.length * bits_per_char * (1.0 - finding.predictability)
        steps.append(
            AttackStep(
                label=label,
                detail=detail,
                guesses=2.0**bits,
                bits=bits,
                kind="pattern",
                span=(finding.start, finding.end),
            )
        )

    # Whatever no detector explained has to be brute-forced.
    covered = sum(f.length for f in strength.findings)
    remaining = strength.length - covered
    if remaining > 0 and bits_per_char > 0:
        bits = remaining * bits_per_char
        steps.append(
            AttackStep(
                label=BRUTE_STEP,
                detail=(
                    f"{remaining} position(s) that no pattern explains, over a "
                    f"{strength.pool_size}-character set"
                ),
                guesses=2.0**bits,
                bits=bits,
                kind="brute",
            )
        )

    # A real attacker spends the cheap guesses first.
    steps.sort(key=lambda step: step.guesses)

    total = 1.0
    for step in steps:
        total *= step.guesses

    plan = AttackPlan(steps=steps, total_guesses=max(total, 1.0))

    if breach is not None and breach.breached:
        # The lookup makes every stage below irrelevant. Keep them, marked as
        # bypassed, because the contrast is the whole point.
        for step in plan.steps:
            step.bypassed = True
        label, detail = BREACH_STEP
        plan.steps.insert(
            0,
            AttackStep(
                label=label,
                detail=(
                    f"{detail}. It appears {breach.count:,} time(s), so it sits "
                    "near the top of the list"
                ),
                guesses=1.0,
                bits=0.0,
                kind="breach",
            ),
        )
        plan.shortcut = True

    return plan


def character_bits(strength: StrengthResult) -> list[float]:
    """Surviving entropy contributed by each position, for the heatmap.

    A position inside a detected pattern keeps only ``1 - predictability`` of
    its nominal bits: that is the part of the character an attacker still has
    to guess after the pattern has narrowed things down.
    """
    bits_per_char = (
        math.log2(strength.pool_size) if strength.pool_size > 1 else 0.0
    )
    bits = [bits_per_char] * strength.length
    for finding in strength.findings:
        for index in range(finding.start, min(finding.end, strength.length)):
            bits[index] = bits_per_char * (1.0 - finding.predictability)
    return bits
